### ISSUE TITLE
为什么会自动将id拼接到labels中？

### ISSUE THREAD

**Issue by dongyuanxin** [gitalk/gitalk#268]
## 问题描述

配置中的`id`会被自动添加到`labels`中。一共几百篇文章都有各自独立的`id`标识，这样创建出来的标签数非常多。

例如下面这种配置：

```javascript
{
  clientID: '...',
  clientSecret: '...',
  repo: 'blog',
  owner: 'dongyuanxin',
  admin: ['dongyuanxin'],
  id: frontmatter.commentid, // 每篇文章的标识
  distractionFreeMode: false
}
```

## 问题定位

在 `src/gitalk.jsx` 中的`createIssue`函数中，对`labels`自动做了拼接。如下图所示：

![image](https://user-images.githubusercontent.com/26399528/59161018-99a4de80-8b0f-11e9-82a8-beb8ab1e8fd8.png)

## 想法建议

是否可以提供配置项，让用户自己决定是否拼接？

**Comment by dongyuanxin** [comment]
PR: [https://github.com/gitalk/gitalk/pull/269](https://github.com/gitalk/gitalk/pull/269)

**Comment by miaowm5** [comment]
纯粹因为最省事吧？

https://github.com/gitalk/gitalk/blob/71db14c2699d618307c86a08903201aeddaa91d0/src/gitalk.jsx#L223
https://developer.github.com/v3/issues/#list-issues-for-a-repository
用的是 list issue 的 api ，要解决的其实是在 issue 人人都能创建的情况下，根据一个文章ID寻找对应的 issue
milestone
state
assignee
mentioned
since
这几个过滤参数可以排除了
sort
direction
这几个过滤条件可以排除了

title 第一眼觉得可行，找 文章ID 对应 title 的 issue 呗，但 issue 人人都能创建有人搞破坏跑去创建几个同名 issue 就炸了，所以 label 这种管理员才能加的内容就被当成检索条件了

要干掉 issue 也有几个思路，
比如检索 creator 是仓库拥有者，且 title 是 文章ID 的 issue 就行了，不过兼容性上算是 break change 了，用旧版本 gitalk 的人更新到新版后评论数据全炸了
