### ISSUE TITLE
Stupid question: is there a secure way to specify `clientSecret`?

### ISSUE THREAD

**Issue by jdossgollin** [gitalk/gitalk#339]
To make gitalk work, we're supposed to specify some information from oauth as follows:

```
const gitalk = new Gitalk({
  clientID: 'GitHub Application Client ID',
  clientSecret: 'GitHub Application Client Secret',
  repo: 'GitHub repo',
  owner: 'GitHub repo owner',
  admin: ['GitHub repo owner and collaborators, only these guys can initialize github issues'],
  id: location.pathname,      // Ensure uniqueness and length less than 50
  distractionFreeMode: false  // Facebook-like distraction free mode
})

gitalk.render('gitalk-container')
```

My question is whether it's a security hazard to have the clientID and clientSecret pasted in that location, and of not whether there's a better, more secure way to store it. (I tend to use jekyll and GitHub pages..)

Thanks for any guidance; I'm aware that this is something of a stupid question

**Comment by TheFirstMe** [comment]
@jdossgollin Have you tried using environment variables?

**Comment by jdossgollin** [comment]
@TheFirstMe Yeah that could certainly work, just wanted to confirm that putting it directly in the config is a bad idea...

**Comment by TheFirstMe** [comment]
@jdossgollin Putting in secret keys directly is definitely a bad idea.

**Comment by Cloud-Forge** [comment]
I am trying to figure out how to use environment variables on my hugo website ... 
but since it's a static site... I don't think I can.

 I tried to use jsdom with firebase functions to create the DOM object directly in the cloud and
return the comment section as an html object. 
but there are too many things to rewrite for it to work. 

Now I am trying to create the 
`new Gitalk({`...})
object with a firebase function then load the object on the load.
from an  xhr call .
 to be able to call, this way the sensitive secret is encapsulated and safe.
`gitalk.render('gitalk-container')`

Is there an easier and safer way to use Gitalk in static site (hosted with firebase) ?

**Comment by krasimir** [comment]
Probably I'm missing something but ... isn't it Gitalk a client-side plugin/library. As such we have to initialize the gitalk instance on the page. So, even if I put my secret in a env variable at the end will be dumped into the html that the browser loads so it is publicly available. Am I missing something here?

**Comment by jdanyow** [comment]
Secure alternative: https://utteranc.es :crystal_ball: 
(full disclosure- I am the maintainer)

**Comment by booxood** [comment]
Safe. So far so good.

Although `clientSecret` is public, but request Github api need is `access_token`. When use `clientSecret` to get `access_token`, it will jump to your configured `Authorization callback URL`, and other users won't be able to use your `clientSecret`  on their site.

If find any **NO SAFE**, please open an issue or PR. :wink:

**Comment by booxood** [comment]
Maybe have better solution. Welcome keep talking.

The https://utteranc.es seems to be pretty good. Should can  refer to.
